# Generated by Django 5.0.7 on 2024-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=11)),
                ('about', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('worker', models.CharField(max_length=30)),
                ('in_archive', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
