# Generated by Django 5.1 on 2024-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_notice_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettersTais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=10)),
                ('theme', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('to_whom', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('worker', models.CharField(max_length=30)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-notification'],
            },
        ),
        migrations.CreateModel(
            name='LettersTeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=10)),
                ('theme', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('to_whom', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('worker', models.CharField(max_length=30)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-notification'],
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-notification']},
        ),
    ]
