# Generated by Django 5.0.7 on 2024-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_letterstais_lettersteks_alter_notice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['-surname'],
            },
        ),
    ]
