# Generated by Django 5.0.7 on 2024-08-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_stages_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='letterstais',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='lettersteks',
            name='theme',
        ),
        migrations.AddField(
            model_name='letterstais',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
        migrations.AddField(
            model_name='lettersteks',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
        migrations.CreateModel(
            name='IncomingLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('from_whom', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='LettersTechBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=255)),
                ('to_whom', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('worker', models.CharField(max_length=30)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('notification', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('agreement', models.BooleanField(default=False)),
                ('supplied', models.BooleanField(default=False)),
                ('in_archive', models.BooleanField(default=False)),
                ('inventory_number', models.CharField(max_length=15)),
                ('is_paper_copy_sent', models.BooleanField(default=False)),
                ('is_pdf_copy_sent', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=255)),
                ('letter_for_paper_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.letterstechbureau')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.notice')),
                ('supplied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.letterstais')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.status')),
            ],
        ),
    ]
