# Generated by Django 5.0.7 on 2024-08-22 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_status_remove_letterstais_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='theme',
        ),
        migrations.AddField(
            model_name='notice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
