# Generated by Django 5.1 on 2024-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_notice_theme_notice_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stages',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
